# Generated by Django 3.2.8 on 2021-10-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Not looking for a job', 'Not Looking'), ('Just watching', 'Just Watching'), ('Looking for a job', 'Looking For Job')], max_length=100)),
                ('grade', models.PositiveSmallIntegerField()),
                ('specialty', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('education', models.CharField(choices=[('Secondary', 'Secondary'), ('Higher', 'Higher')], max_length=25)),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
