# Generated by Django 3.2.8 on 2021-10-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not Looking'), (1, 'Just Watching'), (2, 'Looking For Job')])),
                ('grade', models.PositiveSmallIntegerField()),
                ('specialty', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('education', models.SmallIntegerField(choices=[(0, 'Secondary'), (1, 'Higher')])),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
